apiVersion: batch/v1
kind: CronJob
metadata:
  name: scripy-web
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scripy-web
            image: kran13200/simple-scripy:latest
            imagePullPolicy: IfNotPresent
            env:
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: ckan-token
                    key: token
              - name: WEB_SCRIPY
                value: https://docs.google.com/spreadsheets/d/e/2PACX-1vQlEs3FxFPwm-dpvU1YdsfRgsbfT9WdiXJHZm9kJgGTziPnk-y3TWtftbSbxj6Fe_g0NxYgqyVHTVU5/pubhtml?gid=1397577608&amp;single=true&amp;widget=true&amp;headers=false
            command:
            - python
            - scripy.py
          restartPolicy: OnFailure